name: intro
version: 0.0.1.0
synopsis: Total, Texty, Transformer-Prelude
description: Total, Text, Transformer-Prelude
category: Prelude
author: Daniel Mendler <mail@daniel-mendler.de>
maintainer: Daniel Mendler <mail@daniel-mendler.de>
copyright: 2016 Daniel Mendler
license: MIT
github: minad/intro

ghc-options:
- -Wall

dependencies:
- base                 >= 4.9     && < 5.0
- bifunctors           >= 5.4.1   && < 5.5
- binary               >= 0.8.3.0 && < 0.9
- bytestring           >= 0.9     && < 0.11
- containers           >= 0.5.7.1 && < 0.6
- deepseq              >= 1.4.2.0 && < 1.5
- dlist                >= 0.8.0.2 && < 0.9
- extra                >= 1.5.1   && < 1.6
- hashable             >= 1.2.4.0 && < 1.3
- mtl                  >= 2.2.1   && < 2.3
- safe                 >= 0.3.10  && < 0.4
- string-conversions   >= 0.4     && < 0.5
- tagged               >= 0.8.5   && < 0.9
- text                 >= 0.7     && < 1.3
- transformers         >= 0.5.2.0 && < 0.6
- unordered-containers >= 0.2.7.1 && < 0.3
- writer-cps-mtl       >= 0.1.1   && < 0.2

tested-with:
  GHC == 8.0.1

library:
  source-dirs: src
