name: intro
version: 0.1.0.2
synopsis: '"Fixed Prelude" - Mostly total and safe, provides Text and Monad transformers'
description: |
  Intro is a modern Prelude which provides safe alternatives
  for most of the partial functions and follows other
  best practices, e.g., Text is preferred over String.
  For String overloading the extension 'OverloadedStrings' should be used.
  Container types and Monad transformers are provided.

  Most important - this Prelude tries not to be too fancy.
  This means it just reexports from base and commonly used libraries
  and doesn\'t invent its own stuff.

  Furthermore the Prelude is
  not scattered over multiple files to keep things simple.
  Everything is exported explicitly to improve the quality of the documentation.
category: Prelude
stability: experimental
author: Daniel Mendler <mail@daniel-mendler.de>
maintainer: Daniel Mendler <mail@daniel-mendler.de>
copyright: 2016 Daniel Mendler
license: MIT
github: minad/intro

extra-source-files:
- "*.md"

ghc-options:
- -Wall

dependencies:
- base                 >= 4.8   && < 5.0
- bifunctors           >= 5.2   && < 5.5
- binary               >= 0.7   && < 0.9
- bytestring           >= 0.9   && < 0.11
- containers           >= 0.5   && < 0.6
- deepseq              >= 1.4   && < 1.5
- dlist                >= 0.7   && < 0.9
- extra                >= 1.5.1 && < 1.6
- hashable             >= 1.2.5 && < 1.3
- mtl                  >= 2.2   && < 2.3
- safe                 >= 0.3   && < 0.4
- string-conversions   >= 0.4   && < 0.5
- tagged               >= 0.8   && < 0.9
- text                 >= 0.7   && < 1.3
- transformers         >= 0.4   && < 0.6
- unordered-containers >= 0.2   && < 0.3
- writer-cps-mtl       >= 0.1   && < 0.2

when:
  - condition: impl(ghc < 8.0)
    dependencies: semigroups >= 0.9 && < 1

tested-with:
  GHC == 7.10.3,
  GHC == 8.0.1

library:
  source-dirs: src
  exposed-modules: Intro

tests:
  compat:
    main: compat.hs
    source-dirs: test
    dependencies:
      - intro
      - lens
